/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaMain */

#ifndef _Included_JavaMain
#define _Included_JavaMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaMain
 * Method:    show
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaMain_show
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
