/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eric_demo_JavaMain */

#ifndef _Included_com_eric_demo_JavaMain
#define _Included_com_eric_demo_JavaMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eric_demo_JavaMain
 * Method:    show
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eric_demo_JavaMain_show
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
